version: "3"

services:

  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NASA_API=CUPelPAr06Zrk7XMY3pfIxbv6mcjnKxWkMX7BUe9
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:alpine
    ports:
      - 6379:6379